### ISSUE TITLE
Error: Property 'properties' does not exist on type '{ object: "page"; id: string; }' - v0.4.11

### ISSUE THREAD

**Issue by dharshatharan** [makenotion/notion-sdk-js#247]
**Describe the bug**
When I upgrade from `v0.4.9` to `v0.4.11`, I get type errors in my code that look like this
```
Property 'properties' does not exist on type '{ object: "page"; id: string; }'
```
Seems like the recent type updates in the `api-endpoints.ts` file has new types that look similar to the following that cause the error:
```typescript
{
    ...
        object: "page";
        id: string;
        created_time: string;
        last_edited_time: string;
        archived: boolean;
        url: string;
    } | {
        object: "page";
        id: string;
    }>;
```
and
```typescript
{
    ...
} | {
    object: "block";
    id: string;
}
```

**To Reproduce**
Node version: `v16.13.0`
Notion JS library version: `v0.4.11`

Steps to reproduce the behaviour:
Try running a similar code snippet with `v0.4.11` to make a notion query and parse some data and you will notice `item.properties` throws a `ts(2339)` error. So will `item.icon`.
```typescript
export async function getBookmarks() {
  const { results } = await notion.databases.query({
    database_id: process.env.NOTION_BOOKMARKS_DATABASE ?? "",
    filter: {
      property: "Status",
      select: {
        equals: "Published",
      },
    },
  });
  return results.map((item) => {
    const properties = item.properties;
    return {
      id: item.id,
      emoji: item?.icon?.type === "emoji" ? item.icon.emoji : "",
      createdAt:
        properties.Created.type === "created_time"
          ? properties.Created.created_time
          : "",
      name:
        properties.Name.type === "title"
          ? properties.Name.title[0].plain_text
          : "",
      type: properties.Type.type === "select" ? properties.Type.select : "",
      url: properties.URL.type === "url" ? properties.URL.url : "",
    } as Bookmark;
  });
}
```

**Expected behaviour**
This wasn't the behaviour prior to the upgrade. `v0.4.9` didn't throw these errors. These extra types seem redundant and don't look like they belong there. Why would you have a page or block type that only has an id and no other metadata (created_time, URL, etc)?

Is this something that needs to be fixed? Is there a way to work around this? 

**Screenshots**
![image](https://user-images.githubusercontent.com/43640229/147509145-6abdaada-4910-440d-a0b3-8c64a8896e57.png)
![image](https://user-images.githubusercontent.com/43640229/147509431-237adfb3-62e3-4cc2-abf6-8cef76c36879.png)

**Comment by bwyx** [comment]
I ran into this too but don't see this as unexpected behaviour because i installed it on `v0.4.11` and just assumed it belonged there. so i manually check them like this
![Screenshot_2022-01-03_22-08-22](https://user-images.githubusercontent.com/37757388/147946646-ef639cdf-5e8a-4e7a-ac70-36f6eeb86eba.png)

i think that types should be fixed since this method is very annoying

**Comment by brennengarland** [comment]
I'm having the same problem

**Comment by alexeagleson** [comment]
I'm having the same problem as well.  To me this seems like a significant breaking change for anyone doing DB queries with Typescript.  The new v 0.4.12 from a couple days ago doesn't fix this.

I'm stuck on 0.4.9 until this issue is addressed

**Comment by dca123** [comment]
I too ran into this issue. The problem seems to be the use of a Union and thus typescript defaults to `{ object: "page"; id: string }`. To go around this, you would have to use `if (property in results)`.  With this change, properties become an optional value, which will be shown along with a `?` in intellisense.

**Comment by rhart92** [comment]
Apologies for the issues. The type was expanded to include:

```ts
{
    object: "block";
    id: string;
}
```

so that we are able to return pages that a bot doesn't have access to. In this case, we return the objects `type` and `id` to indicate that it exists but won't return all the details since the bot doesn't have access.

In order to fix the typescript errors, you'll have to check for the existence of a key that only exists if the bot had access, e.g. `properties`. You could also write a type guard that would do the check for you to make it a bit DRYer.

**Comment by AakashMallik** [comment]
@rhart92 This `PartialBlockObjectResponse` and `BlockObjectResponse` are not exported members of the `@notionhq/client/build/src/api-endpoints` file. How can we write a type guard without access to them individually? For now, I am resorting to `in` but not a very great solution. Do we plan on exposing the individual types?

**Comment by TheMrZZ** [comment]
At this point, we've gone full circle with #219 "Question about new typings":

* `@notionhq/client` does not export individual types
* We were able to extract them before using some [complicated methods](https://github.com/nartc/notion-stuff/blob/6e22fbffafb528e41cc31258c34b5234048ebb25/libs/v4-types/src/lib/types.ts#L6)
* But now that the response include partial pages, even that doesn't work anymore

The DX is getting worse, while the API is improving - it's a bit weird.

**Comment by pspeter3** [comment]
I wonder if the SDK can export the type guards necessary to help improve the DX?
